-- SyncFin — schema PostgreSQL (substitui o schema Oracle usado na avaliação FIAP).
-- Identificadores ficam propositalmente SEM ASPAS: o PostgreSQL dobra identificador
-- não citado para minúsculo, e toda DAO já usa identificadores não citados nas
-- queries e rs.getString("EMAIL") (busca case-insensitive por spec do JDBC) —
-- então nada aqui exige mudança de Java por causa de case.

BEGIN;

DROP TABLE IF EXISTS T_INVESTIMENTO CASCADE;
DROP TABLE IF EXISTS T_DESPESA CASCADE;
DROP TABLE IF EXISTS T_RECEITA CASCADE;
DROP TABLE IF EXISTS T_CONTA_BANCARIA CASCADE;
DROP TABLE IF EXISTS T_CLIENTE CASCADE;

CREATE TABLE T_CLIENTE (
    ID_CLIENTE      INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NM_CLIENTE      VARCHAR(150) NOT NULL,
    NR_CELULAR      VARCHAR(20)  NOT NULL,
    NR_CPF          VARCHAR(14)  NOT NULL UNIQUE,
    EMAIL           VARCHAR(150) NOT NULL UNIQUE,
    SENHA           VARCHAR(100) NOT NULL,   -- hash BCrypt tem 60 caracteres; 100 dá folga
    ST_CONTA        VARCHAR(10)  NOT NULL DEFAULT 'Ativa',
    DT_CADASTRO     TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE T_CONTA_BANCARIA (
    ID_CONTA        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE      INTEGER NOT NULL REFERENCES T_CLIENTE (ID_CLIENTE) ON DELETE CASCADE,
    NM_INSTITUICAO  VARCHAR(100) NOT NULL,
    AGENCIA         VARCHAR(20)  NOT NULL,
    NR_CONTA        VARCHAR(20)  NOT NULL,
    TIPO_CONTA      VARCHAR(30)  NOT NULL,
    SALDO_ATUAL     DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE T_RECEITA (
    ID_RECEITA        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE        INTEGER NOT NULL REFERENCES T_CLIENTE (ID_CLIENTE) ON DELETE CASCADE,
    ID_CONTA          INTEGER NOT NULL REFERENCES T_CONTA_BANCARIA (ID_CONTA) ON DELETE CASCADE,
    VL_RECEITA        DOUBLE PRECISION NOT NULL,
    CATEGORIA_RECEITA VARCHAR(50)  NOT NULL,
    DT_RECEBIMENTO    DATE NOT NULL,
    OB_RECEITA        VARCHAR(255),
    ST_RECEITA        VARCHAR(20) NOT NULL
);

CREATE TABLE T_DESPESA (
    ID_DESPESA         INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE         INTEGER NOT NULL REFERENCES T_CLIENTE (ID_CLIENTE) ON DELETE CASCADE,
    ID_CONTA           INTEGER NOT NULL REFERENCES T_CONTA_BANCARIA (ID_CONTA) ON DELETE CASCADE,
    VL_DESPESA         DOUBLE PRECISION NOT NULL,
    CATEGORIA_DESPESA  VARCHAR(50) NOT NULL,
    DT_VENCIMENTO      DATE NOT NULL,
    OB_DESPESA         VARCHAR(255),
    ST_DESPESA         VARCHAR(20) NOT NULL
);

CREATE TABLE T_INVESTIMENTO (
    ID_INVESTIMENTO   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE        INTEGER NOT NULL REFERENCES T_CLIENTE (ID_CLIENTE) ON DELETE CASCADE,
    ID_CONTA          INTEGER NOT NULL REFERENCES T_CONTA_BANCARIA (ID_CONTA) ON DELETE CASCADE,
    TIPO_INVESTIMENTO VARCHAR(50) NOT NULL,
    VL_INVESTIMENTO   DOUBLE PRECISION NOT NULL,
    DT_INVESTIMENTO   DATE NOT NULL,
    RECORRENCIA       VARCHAR(20),
    ST_INVESTIMENTO   VARCHAR(20) NOT NULL,
    RENDIMENTO        DOUBLE PRECISION NOT NULL DEFAULT 0,
    DT_VENCIMENTO     DATE   -- opcional: InvestimentoDao faz setNull(Types.DATE) quando ausente
);

CREATE INDEX IDX_CONTA_CLIENTE        ON T_CONTA_BANCARIA (ID_CLIENTE);
CREATE INDEX IDX_RECEITA_CLIENTE      ON T_RECEITA (ID_CLIENTE);
CREATE INDEX IDX_DESPESA_CLIENTE      ON T_DESPESA (ID_CLIENTE);
CREATE INDEX IDX_INVESTIMENTO_CLIENTE ON T_INVESTIMENTO (ID_CLIENTE);

COMMIT;
